#!/bin/bash
ID=$1

cpu() {
  data='<span style="color: #AAAAAA"> CPU </span>'
  data+='<span style="color: #82A5D0">｜</span>'
  #if [[ "$HOSTNAME" == "switch" ]]; then
  #  data+="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq | awk 'NR==1{printf "%.2f",$1/1000000}')GHz"
  #else
	#	data+="$(cat /proc/cpuinfo | grep MHz | awk 'NR==1{printf "%.2f",$4/1000}')GHz"
  #fi
  #data+="<b>$(top -b -n 1 | grep Cpu | awk '{print $2}' | sed s/,/./g)%</b>"
  data+="<b>$(top -bn2 -d 0.1 | awk '/Cpu/ {print $2}' | awk 'NR==2')%</b>"
  #printf "%s" "$data"
  printf "| A | %s | | |" "$data"
}

temp() {
	data='<span style="color: #AAAAAA"> Temp </span>'
  data+='<span style="color: #82A5D0">｜</span>'
  data+='<b>'
  case $HOSTNAME in
    "compy")
			# data+="$(sensors | awk 'NR==13{printf $2}' | cut -d"+" -f2)"
      data+="$(sensors | grep edge | awk '{printf $2}' | cut -d'+' -f2)"
      ;;
    "laptop")
			data+="$(sensors | grep "Core 0" | awk '{printf $3}' | cut -d"+" -f2)"
      ;;
    "nobus")
			data+="$(sensors | grep "Core 0" | awk '{printf $3}' | cut -d"+" -f2)"
      ;;
    "switch")
			data+="$(sensors | awk 'NR==7{printf $2}' | cut -d"+" -f2)"
      ;;
  esac
  data+="</b>"
  #printf "%s" "$data"
  printf "| A | %s | | |" "$data"
}

ram() {	
  data='<span style="color: #AAAAAA"> RAM </span>'
  data+='<span style="color: #82A5D0">｜</span>'
  #data+="<b>$(free --mebi | awk 'NR==2{printf "%sMiB %.0f%%", $3,$3*100/$2}')</b>"
  data+="<b>$(free --mebi | awk 'NR==2{printf "%sMiB", $3}')</b>"
  #printf "%s" "$data"
  printf "| A | %s | | |" "$data"
}

swap() {
  data='<span style="color: #AAAAAA"> SWAP </span>'
  data+='<span style="color: #82A5D0">｜</span>'
  #data+="<b>$(free --mebi | awk 'NR==3{printf "%sMiB %.0f%%", $3,$3*100/$2 }')</b>"
  data+="<b>$(free --mebi | awk 'NR==3{printf "%sMiB", $3}')</b>"
  #printf "%s" "$data"
  printf "| A | %s | | |" "$data"
}

vram() {
  data='<span style="color: #AAAAAA"> VRAM </span>'
  data+='<span style="color: #82A5D0">｜</span>'
  data+="<b>$(radeontop -l 1 -t 1 -i 1 -d - | awk 'NR==2{printf "%.0f",$28}')MiB</b>"
  #printf "%s" "$data"
  printf "| A | %s | | |" "$data"
}

toggle_enabled () {
  data='<span style="color: #AAAAAA"> 󰁓 </span>'
  printf "| A | %s | | |" "$data"
}

while true
do
	timer="1s"

  #DATA="| A | $(cpu) | | |"
  #DATA+="| A | $(temp) | | |"
  #DATA+="| A | $(ram) | | |"
  #DATA+="| A | $(swap) | | |"
  DATA="$(cpu)"
  DATA+="$(temp)"
  DATA+="$(ram)"
  DATA+="$(swap)"

  if [[ "$HOSTNAME" == "compy" ]]; then
    #DATA+="| A | $(vram) | | |"
    DATA+="$(vram)"
    timer="0s"
  fi

  #DATA+="$(toggle_enabled)"
    
	if [[ -n "$1" ]]; then
		qdbus org.kde.plasma.doityourselfbar /id_$ID \
			org.kde.plasma.doityourselfbar.pass "$DATA"
	else
		echo "$DATA"
	fi

  sleep "$timer"
done
